# IMPUTACIÓN POR PROPAGACIÓN HACIA ADELANTE Y HACIA ATRAS

## PROPAGACIÓN HACIA ADELANTE (FFILL)

In [1]:
import pandas as pd
data = pd.Series([1,None,None,4])
data

0    1.0
1    NaN
2    NaN
3    4.0
dtype: float64

In [2]:
data.ffill()

0    1.0
1    1.0
2    1.0
3    4.0
dtype: float64

## PROPAGACIÓN HACIA ATRÁS (BFILL)

In [3]:
data.bfill()

0    1.0
1    4.0
2    4.0
3    4.0
dtype: float64

## IMPUTACIÓN POR INTERPOLACIÓN (INTERPOLATE)

In [4]:
data.interpolate()

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64